
---
# Source: qdrant/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: qdrant
  labels:
    app: qdrant
    app.kubernetes.io/name: qdrant
    app.kubernetes.io/instance: qdrant
    app.kubernetes.io/version: "v1.18.2"
