---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: cluster-vikunja
spec:
  instances: 1
  bootstrap:
    initdb:
      database: vikunja
      secret:
        name: vikunja-credentials
      import:
        type: microservice
        databases:
          - vikunja
  storage:
    size: 8Gi
