
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dawarich-pvc-watched
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: longhorn   
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dawarich-pvc-storage
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: longhorn   
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dawarich-pvc-public
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: longhorn   
