apiVersion: apps/v1
kind: Deployment
metadata:
  name: opa
spec:
  replicas: 2
  selector:
    matchLabels:
      app: opa
  template:
    metadata:
      labels:
        app: opa
    spec:
      containers:
        - name: opa
          image: openpolicyagent/opa:1.16.1
          args:
          - "run"
          - "--server"
          - "--addr=:8181"
          - "--config-file=/etc/opa/config.yaml"
          - "/etc/opa/policies"
          ports:
            - containerPort: 8181
          livenessProbe:
            httpGet:
              path: /health/live
              port: 8181
            initialDelaySeconds: 15
          readinessProbe:
            httpGet:
              path: /health/ready # Detail view for debugging
              port: 8181
            initialDelaySeconds: 15
          volumeMounts:
            # Mount the specific file to avoid directory collisions
            - name: opa-config-vol
              mountPath: /etc/opa/config.yaml
              subPath: opa-config.yaml 
            - name: opa-policy-vol
              mountPath: /etc/opa/policies/policy.rego
              subPath: policy.rego
            - name: opa-healthcheck-policy-vol
              mountPath: /etc/opa/policies/healthcheck-policy.rego
              subPath: healthcheck-policy.rego
      volumes:
        - name: opa-config-vol
          secret:
            secretName: opa-config
        - name: opa-policy-vol
          configMap:
            name: opa-policies
        - name: opa-healthcheck-policy-vol
          configMap:
            name: opa-healthcheck-policies
