apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: homelab-issuer
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: homelab-ca-issuer
spec:
  ca:
    secretName: homelab-ca-secret
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: homelab-ca
  namespace: cert-manager
spec:
  isCA: true
  commonName: ca.nauvis.lan
  secretName: homelab-ca-secret
  # 87600h is approximately 10 years
  duration: 87600h 
  # Renew the cert 720h (30 days) before it actually expires
  renewBefore: 720h 
  privateKey:
    algorithm: ECDSA
    size: 256
  issuerRef:
    name: homelab-issuer
    kind: ClusterIssuer
    group: cert-manager.io
