apiVersion: v1
kind: Secret
data:
  ca.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJjekNDQVJxZ0F3SUJBZ0lVSjMvTkdGRC9vTUkwSmhPV0p4VUcxOVpFY3Nnd0NnWUlLb1pJemowRUF3SXcKR0RFV01CUUdBMVVFQXhNTlkyRXVibUYxZG1sekxteGhiakFlRncweU5qQXlNREV4TlRReU16VmFGdzB6TmpBeApNekF4TlRReU16VmFNQmd4RmpBVUJnTlZCQU1URFdOaExtNWhkWFpwY3k1c1lXNHdXVEFUQmdjcWhrak9QUUlCCkJnZ3Foa2pPUFFNQkJ3TkNBQVFxM1hXL1pXd1c4VUtkNi82UTN1NElJalVINzhlaDFkbDhhMUMxajh6UjdoMmoKQ0FCK01lWmZtNFZJczJjRzEvQWtZbUF0WndoQWlGYnhKL0lUdEdpOG8wSXdRREFPQmdOVkhROEJBZjhFQkFNQwpBcVF3RHdZRFZSMFRBUUgvQkFVd0F3RUIvekFkQmdOVkhRNEVGZ1FVdDNPWUVYUFJoamlDbVhiWFd2N3JmNWhlCmE4b3dDZ1lJS29aSXpqMEVBd0lEUndBd1JBSWdWdkZNTStnYUk1S3k5RmZwRys1T0kzS0xNd0pJY1V0aVJMaWoKcEtXWVhKb0NJQ1lqNk9pOVZ4VEMybXIyNjlwKzVKWWdEVkhsekkzd21pL3I5Rzh3aVdlawotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
metadata:
  name: nauvis-ca-tls
