apiVersion: v1
kind: Pod
metadata:
  name: dawarich-db-migrate
spec:
  restartPolicy: Never
  containers:
    - name: migration-runner
      image: freikin/dawarich:1.8.1
      command: ["bin/rails", "db:migrate"]
      # Reuse the exact same environment variables/configmap/secrets your main deployment uses
      env:
        - name: SAFETY_ASSURED
          value: "true"
        - name: SKIP_DATA_MIGRATIONS
          value: "true"
        - name: TIME_ZONE
          value: "Europe/Amsterdam"
        - name: RAILS_ENV
          value: development
        - name: REDIS_URL
          value: redis://dawarich-svc-redis:6379
        - name: DATABASE_HOST
          value: dawarich-svc-postgis
        - name: DATABASE_PORT
          value: "5432"
        - name: DATABASE_USERNAME
          valueFrom:
            secretKeyRef:
              name: dawarich-secret-postgis
              key: POSTGRES_USER
        - name: DATABASE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: dawarich-secret-postgis
              key: POSTGRES_PASSWORD
        - name: DATABASE_NAME
          valueFrom:
            secretKeyRef:
              name: dawarich-secret-postgis
              key: POSTGRES_DB  
        - name: APPLICATION_HOST
          value: localhost
        - name: APPLICATION_HOSTS
          value: "dawarich.nauvis.lan,dawarich.pieter.fish,localhost"
        - name: APPLICATION_PROTOCOL
          value: http
        - name: PHOTON_API_HOST
          value: photon.komoot.io
        - name: PHOTON_API_USE_HTTPS
          value: "true"
        - name: RAILS_MIN_THREADS
          value: "5"
        - name: RAILS_MAX_THREADS
          value: "10"
