apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: immich-manifests
  namespace: argocd
spec:
  project: default
  source:
    repoURL: ssh://git@git.pieter.fish/pieter/argocd-manifests.git
    targetRevision: HEAD
    path: immich/
    kustomize: {}
  destination:
    server: https://kubernetes.default.svc
    namespace: immich
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
      - CreateNameSpace=true
