apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mcp
  namespace: argocd
spec:
  project: default
  source:
    repoURL: ssh://git@git.pieter.fish/pieter/go-git-rag.git
    targetRevision: HEAD
    path: k8s/
    directory:
      recurse: true
  destination:
    namespace: git-mcp
    server: https://kubernetes.default.svc
  syncPolicy:
    managedNamespaceMetadata:
      labels:
        gateway-access: true
    automated:
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
