apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pieter-fish
  namespace: argocd
spec:
  project: default
  source:
    repoURL: git@github.com:Pieter-Visscher/kubernetes-argo.git
    targetRevision: HEAD
    path: pieter-fish/
    directory:
      recurse: true
  destination:
    namespace: pieter-fish-website
    server: https://kubernetes.default.svc
  syncPolicy:
    managedNamespaceMetadata:
      labels:
        wan-gateway-access: true
    automated:
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
