---
apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: uboulder-01
  labels:
    app: uboulder-01
spec:
  running: true
  template:
    metadata:
      labels:
        kubevirt.io/domain: uboulder-01
    spec:
      domain:
        features:
          hyperv:
            relaxed: { enabled: true }
            vapic: { enabled: true }
            spinlocks: { enabled: true }
          acpi: {}
        firmware:
          bootloader:
            efi:
              secureBoot: false
        cpu:
          cores: 4
        devices:
          disks:
            - name: bootdisk
              disk:
                bus: virtio
            - name: cloudinit
              disk:
                bus: virtio
          interfaces:
            - name: default
              bridge: {}
        resources:
          requests:
            memory: 4Gi
      networks:
        - name: default
          multus:
            networkName: services-vlan
      volumes:
        - name: bootdisk
          dataVolume:
            name: uboulder-web01-disk-image
        - name: cloudinit
          cloudInitNoCloud:
            userDataSecretRef:
              name: uboulder-01-cloudinit
---
apiVersion: v1
kind: Secret
metadata:
  name: uboulder-01-cloudinit
type: Opaque
data:
  userdata: I2Nsb3VkLWNvbmZpZwp1c2VyczoKICAtIG5hbWU6IHBpZXRlcgogICAgZ3JvdXBzOiBzdWRvCiAgICBzdWRvOiBBTEw9KEFMTCkgTk9QQVNTV0Q6QUxMCiAgICBzaGVsbDogL2Jpbi9iYXNoCiAgICBsb2NrX3Bhc3N3ZDogZmFsc2UKICAgIHNzaF9hdXRob3JpemVkX2tleXM6CiAgICAgIC0gc3NoLXJzYSBBQUFBQjNOemFDMXljMkVBQUFBREFRQUJBQUFDQVFERnZzTC9tNWphdHBZbmJzallRS2YrcEJIZmN1bWhnR1NxdVcrSVI5RENZUmFYNmZTZWxmdnRWVWptSXdTNjNwV3hZWlVVMlozYzVhblZrZUgxVEIya0VoVVo2QWo1NVdJNkhXbnlZM0szWnduUjlNWXlGcWExVDhwc0Y2UkFidmxJRlZKMEhZZzJKamNJTnNLSjhZOHVpanJtdDdtK1BrL2FjaVBKZTV0ck9qTGNRWnQ2QWk2ZmdmblNkZEgyaWVoTlo0WCtxMk5sNlhRbWtkUmFaOTJaMWZaV3RFUnExbkVqTktmWG55NTIzTzdlcGtybHd4YVZOakpCSnFXVTkvZ1Q0ZnZuMnhEMUZBR3VtSk13STF4YTlkR1JVb290ZHVCMTFkQm14eXQ2OFpHbHU2OW9NK2lRalBqaC9zM0R6N1FxUzRaRGZBQmhweU1BRFJENFFEZVRTMmY4am9SdFpsMUNQdWRkdVpGZng2N1E3WEJrWUxnOWw3c0lzdzM3UmFMc3pDMG16WU9XQ1JZWVRTOERDb0R3N3NaREZnOVJtYTF1WmlpeTJkZHIrcm05alhhVm5aT21aR2RBWXFSRHV0V1BxN21hc1JYUXp2d25yVi92YTNkdlhBQ25Td0FRWUR0aHhRcTM2NThKTTFGTHkyZi9BVGJ6c3NDd2FLSmhLYjBGSlM5M29LVC9FUEtpbU1rY1I2Q0NPNTFtYVNLL1dZRmkzTUtxUkZ6VjZYYzlEaTVNZFF3WTNUclNHL0wzTnJKOVpMaHMyejM4cGVyd2JKaHpHcXZHSTNxZFdWSjFnMitISVdxZGtCK0ZmWGdRUjVWVHRPaDNnbDVSR2pteGhkV0hkb2cvUkVsRXhUMlZiREpvMUhHSHAyVEtQb21xL0c1UHFiZXpZcXNRVFE9PSBwaWV0ZXJAUGlldGVycy1NYWNCb29rLVByby5sb2NhbAogICAgICAtIHNzaC1yc2EgQUFBQUIzTnphQzF5YzJFQUFBQURBUUFCQUFBQmdRQ3JqRmNORSt6ejJObWVqRXEwNE9vM1UyWEdBZFBHdEthNDJROGVJUGM4bWV6UVduOWN2K0s0RFpNNEJIb21oVmY5dXJQZzV6dG1FR0l5a016QkhvV3lJZC9XcHlvaWZZdjJqZTRBa05GeWFNU0d0b3ZNUXpLZjZlZ0hOdGR1a1ptOE1obHZIME9IVVJSaTA5REViT1pOR0xpMXFKdFdPbFBiNUg4WWRIalNUMEJkemRlb3V1eExzV2EyNFlvb01XRUJaaWxCcHFaNVJNQ3c2U1AvS3RQMEtHSDR1TlE1U1JQa05VTXBBR3QvNkxkWjFaajE2R016bWRyZzJUa0xUTlhubUpva0dmZTZIT3JKa1EydzYzdnN4VzZkWDJ1b3AzUERmc3dkaHNlZmM1ekZlQVRLMC9tcnJwVHZPTFp4TjhVMy9oZitEbG1ORFBaVC9kTGhtV0NINXJuNlBiUzBSd0VWSThxTTJNU0hjSVZCcXVJbHExaGFtMFlhWnJTOGFIVzQ4TFo4SnNOK2ZZSEEvWDZxUzVtWG1HT0VLYnNrY0pBZzFWdWRpREExbXU3RFBDdlE5QitpZWZ2dkJPbVQ4eWFkOFkxYTlRVG41NjFwdFRPaEdCcGdIaGp4MG53TUpQWVJaYk1saGo0Tk1CTktzak1OUVJxd244d0l4YUo1cUJrPSBwaWV0ZXJAZGViaWFuCmNocGFzc3dkOgogIGV4cGlyZTogZmFsc2UKICB1c2VyczoKICAgIC0gbmFtZTogcGlldGVyCiAgICAgIHBhc3N3b3JkOiB0ZXN0MTIzCiAgICAgIHR5cGU6IHRleHQKc3NoX3B3YXV0aDogdHJ1ZQp3cml0ZV9maWxlczoKICAtIHBhdGg6IC9ldGMvTmV0d29ya01hbmFnZXIvc3lzdGVtLWNvbm5lY3Rpb25zL2V0aDAubm1jb25uZWN0aW9uCiAgICBwZXJtaXNzaW9uczogJzA2MDAnCiAgICBjb250ZW50OiB8CiAgICAgIFtjb25uZWN0aW9uXQogICAgICBpZD1ldGgwCiAgICAgIHR5cGU9ZXRoZXJuZXQKICAgICAgaW50ZXJmYWNlLW5hbWU9ZXRoMAoKICAgICAgW2V0aGVybmV0XQoKICAgICAgW2lwdjRdCiAgICAgIG1ldGhvZD1tYW51YWwKICAgICAgYWRkcmVzc2VzPTEwLjAuMjAwLjEwMS8yNAogICAgICBnYXRld2F5PTEwLjAuMjAwLjEKICAgICAgZG5zPTEwLjAuMjAwLjEKICAgICAgaWdub3JlLWF1dG8tZG5zPXRydWUKCiAgICAgIFtpcHY2XQogICAgICBtZXRob2Q9ZGlzYWJsZWQKcnVuY21kOgogIC0gbm1jbGkgY29ubmVjdGlvbiByZWxvYWQKICAtIG5tY2xpIGNvbm5lY3Rpb24gdXAgZXRoMA==
---
apiVersion: cdi.kubevirt.io/v1beta1
kind: DataVolume
metadata:
  name: uboulder-web01-disk-image
spec:
  source:
    http:
      url: "https://repo.almalinux.org/almalinux/10/cloud/x86_64_v2/images/AlmaLinux-10-GenericCloud-latest.x86_64_v2.qcow2"
  pvc:
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: 50Gi
