apiVersion: v1
kind: ConfigMap
metadata:
  name: powerdns-authorative-config
data:
  pdns.conf: |
    local-address=0.0.0.0
    launch=bind
    bind-config=/etc/powerdns/zones/named.conf
    bind-check-interval=60
    bind-ignore-broken-records=yes
    webserver=yes
    webserver-address=0.0.0.0
    webserver-allow-from=0.0.0.0/0,::/0
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: powerdns-recursor-config
data:
  recursor.yml: |
    incoming:
      listen:
        - 0.0.0.0:53
      allow_from:
        - 0.0.0.0/0
    webservice:
      address: 0.0.0.0
      port: 8082
      allow_from:
        - 0.0.0.0/0
      webserver: true
      password: "your_secret_password"
      api_key: "your_secret_key"
    recursor:
      stats_rec_control_disabled_list: []
