---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/instance: woodpecker-ci
    app.kubernetes.io/name: agent
  name: woodpecker-ci-agent
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  labels:
    app.kubernetes.io/instance: woodpecker-ci
    app.kubernetes.io/name: agent
  name: woodpecker-ci-agent
rules:
- apiGroups:
  - ""
  resources:
  - persistentvolumeclaims
  - services
  - secrets
  verbs:
  - create
  - delete
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - watch
  - create
  - delete
  - get
  - list
- apiGroups:
  - ""
  resources:
  - pods/log
  verbs:
  - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    app.kubernetes.io/instance: woodpecker-ci
    app.kubernetes.io/name: agent
  name: woodpecker-ci-agent
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: woodpecker-ci-agent
subjects:
- kind: ServiceAccount
  name: woodpecker-ci-agent
